### ISSUE TITLE
Requesting a dataset

### ISSUE THREAD

**Issue by nebstudio** [xbiome/protein-annotation#1]
Hello, I am very interested in your work, can you provide me with the dataset?

**Comment by CNwangbin** [comment]
Thank you for your interest in our work! The datasets you’re requesting can be accessed here(https://drive.google.com/drive/folders/1uRrwF7eTcJicOpfIIz9mapUkkTt5vYve?usp=sharing).

**Comment by Fpandax** [comment]
您好，请问预测脚本inference_fasta_cpu.py中参数input_file中的fasta文件需要自行找数据集吗？
